CC ?= cc
CFLAGS ?= -O2 -Wall -Wno-unused-function -Wno-unused-variable -DLSB_FIRST -I../core -I../core/z80 -I../main/roms
SRCS = harness.c ../core/gyruss.c ../core/gyruss_video.c ../core/ay8910.c ../core/e6809.c ../core/z80/Z80.c
harness: $(SRCS) ../core/*.h
	$(CC) $(CFLAGS) -o $@ $(SRCS) -lm
clean:
	rm -f harness
