#!/usr/bin/env python3
"""Convert the MAME 'gyruss' ROM set into a C header for TOCCATA.

usage: convert_roms.py <romdir> [outdir]   (default outdir: ../main/roms)

Four processors and three sets of graphics:
  maincpu   32 KB Z80 program
  sub       8 KB at 0xE000 for the KONAMI-1 (a 6809 with scrambled opcodes)
  audiocpu  16 KB Z80 program for the five sound chips
  audio2    4 KB for the 8039 that drives the DAC
  sprites   32 KB, four bitplanes
  tiles     8 KB, two bitplanes
  proms     a 32-byte palette and two 256-byte colour lookup tables
"""
import sys, zlib
from pathlib import Path

MAIN   = [('gyrussk.1', 0x0000, 0x2000, 0xc673b43d),
          ('gyrussk.2', 0x2000, 0x2000, 0xa4ec03e4),
          ('gyrussk.3', 0x4000, 0x2000, 0x27454a98)]
SUB    =  ('gyrussk.9', 0x2000, 0x822bf27e)          # lives at 0xE000 in the 6809's map
AUDIO  = [('gyrussk.1a', 0x0000, 0x2000, 0xf4ae1c17),
          ('gyrussk.2a', 0x2000, 0x2000, 0xba498115)]
AUDIO2 =  ('gyrussk.3a', 0x1000, 0x3f9b5dea)
SPRITES = [('gyrussk.6', 0x0000, 0x2000, 0xc949db10),
           ('gyrussk.5', 0x2000, 0x2000, 0x4f22411a),
           ('gyrussk.8', 0x4000, 0x2000, 0x47cd1fbc),
           ('gyrussk.7', 0x6000, 0x2000, 0x8e8d388c)]
TILES  =  ('gyrussk.4', 0x2000, 0x27d8329b)
PROMS  = [('gyrussk.pr3', 0x20,  0x98782db3),        # palette
          ('gyrussk.pr1', 0x100, 0x7ed057de),        # sprite lookup
          ('gyrussk.pr2', 0x100, 0xde823a81)]        # character lookup

def load(romdir, name, size, want):
    p = romdir / name
    if not p.exists():
        sys.exit(f'error: {name} not found in {romdir}\n'
                 f'       you need MAME\'s "gyruss" set; unzip it there')
    data = p.read_bytes()
    if len(data) != size:
        sys.exit(f'error: {name} is {len(data)} bytes, expected {size}')
    crc = zlib.crc32(data) & 0xffffffff
    if crc != want:
        sys.exit(f'error: {name} has crc32 {crc:08x}, expected {want:08x}\n'
                 f'       this is a different set; TOCCATA is built for "gyruss"')
    print(f'  {name}: {len(data)} bytes, crc32 {crc:08x}')
    return data

def c_array(name, data, dims):
    out = [f'static const uint8_t {name}{dims} = {{']
    for i in range(0, len(data), 24):
        out.append('    ' + ','.join(f'0x{b:02X}' for b in data[i:i+24]) + ',')
    out.append('};')
    return '\n'.join(out)

def main():
    romdir = Path(sys.argv[1] if len(sys.argv) > 1 else 'gyruss')
    outdir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent / 'main' / 'roms'
    outdir.mkdir(parents=True, exist_ok=True)
    print(f'ROMs: {romdir}')

    main_rom = bytearray(0x8000)
    for n, a, s, c in MAIN:
        main_rom[a:a+s] = load(romdir, n, s, c)

    sub = load(romdir, SUB[0], SUB[1], SUB[2])
    audio = bytearray(0x6000)
    for n, a, s, c in AUDIO:
        audio[a:a+s] = load(romdir, n, s, c)
    audio2 = load(romdir, AUDIO2[0], AUDIO2[1], AUDIO2[2])

    spr = bytearray(0x8000)
    for n, a, s, c in SPRITES:
        spr[a:a+s] = load(romdir, n, s, c)
    tiles = load(romdir, TILES[0], TILES[1], TILES[2])
    proms = b''.join(load(romdir, n, s, c) for n, s, c in PROMS)

    out = ['/* gyruss_roms.h - AUTO-GENERATED by tools/convert_roms.py - DO NOT COMMIT */',
           '#ifndef GYRUSS_ROMS_H', '#define GYRUSS_ROMS_H', '#include <stdint.h>', '',
           c_array('gy_rom', bytes(main_rom), '[0x8000]'), '',
           c_array('gy_subrom', sub, '[0x2000]'), '',
           c_array('gy_audiorom', bytes(audio), '[0x6000]'), '',
           c_array('gy_audio2rom', audio2, '[0x1000]'), '',
           c_array('gy_sprites', bytes(spr), '[0x8000]'), '',
           c_array('gy_tiles', tiles, '[0x2000]'), '',
           c_array('gy_proms', proms, '[0x220]'), '',
           '#endif']
    (outdir / 'gyruss_roms.h').write_text('\n'.join(out))
    print(f'wrote {outdir / "gyruss_roms.h"}')

if __name__ == '__main__':
    main()
